11:12:57 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:12:57 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:13:04 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:13:04 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:15:54 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:15:54 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:16:22 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:16:22 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:16:41 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:16:41 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:27:53 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:27:53 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:27:55 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:27:55 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:27:57 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:27:57 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:27:58 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:27:58 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:27:59 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:27:59 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:28:00 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:28:00 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:29:43 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabdawau\xbb\n', 85, 86, 'invalid continuation byte'),)
11:29:43 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:32:06 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  no existe la base de datos \xabdawau\xbb\n', 96, 97, 'invalid start byte'),)
11:32:06 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:32:10 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  no existe la base de datos \xabdawau\xbb\n', 96, 97, 'invalid start byte'),)
11:32:10 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:32:46 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  no existe la base de datos \xabdawau\xbb\n', 96, 97, 'invalid start byte'),)
11:32:46 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:32:56 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "localhost" (::1), port 5432 failed: FATAL:  no existe la base de datos \xabdawau\xbb\n', 96, 97, 'invalid start byte'),)
11:32:56 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
11:48:52 - ERR - login - (TypeError("'int' object is not subscriptable"),)
11:52:46 - ERR - login - (KeyError(0),)
11:53:22 - ERR - login - (AttributeError("'RealDictRow' object has no attribute 'valor'"),)
